# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c708b795d79377682341ade0e6f450beec157117603682cdcde0e558e2bbb32ba3b5e3cf12bcb9c52897949d760812c4a76a887933e0f54835c02cbd8702652f

test:
  secret_key_base: 714a685ec11cea9750adbbed19c793a1c99437d306ffb1a831e43aae8060c07bbce09714373efe42c7eebdbea6b3ca3fe660e06f2a9d748332e11ef65d240c30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
